const mockMovies = [
    {
        "@id": "/api/movies/11",
        "@type": "Movie",
        "title": "Чёрная Вдова",
        "alternativeTitle": null,
        "originalTitle": "Black Widow",
        "slug": "black-widow",
        "description": "Наташе Романофф предстоит лицом к лицу встретиться со своим прошлым. Чёрной Вдове придется вспомнить о том, что было в её жизни задолго до присоединения к команде Мстителей, и узнать об опасном заговоре, в который оказываются втянуты её старые знакомые — Елена, Алексей (известный как Красный Страж) и Мелина.",
        "mainMediaObject": {
            "@id": "/api/media_objects/40",
            "@type": "MediaObject",
            "type": "MOVIE_COVER",
            "dirName": "2020/09",
            "fileName": "fixture_movie_cover_city.jpg",
            "mimeType": "image/jpeg",
            "width": 1023,
            "height": 681,
            "ratio": "1.5022026",
            "author": null,
            "description": null,
            "thumbnailUrl": "/uploads/media/2020/09/fixture_movie_cover_city_th.jpg",
            "url": "/uploads/media/2020/09/fixture_movie_cover_city.jpg"
        },
        "worldPremiereYear": 2021,
        "worldPremiereMonth": 6,
        "worldPremiereDay": 30,
        "russiaPremiereYear": 2021,
        "russiaPremiereMonth": 7,
        "russiaPremiereDay": 8,
        "budget": "$200 000 000",
        "duration": 134,
        "ageRating": "16+",
        "mpaaRating": "PG-13",
        "imdbId": "tt3480822",
        "imdbRating": "6.9",
        "kinopoiskId": "823956",
        "kinopoiskRating": "6.2",
        "website": "",
        "moverTrailerCode": "",
        "publishedCommentsCount": 16,
        "ratesCount": 3,
        "rating": "3.0",
        "genres": [
            {
                "@id": "/api/genres/15",
                "@type": "Genre",
                "name": "Приключения",
                "slug": "adventure",
                "isAppliedToBooks": false,
                "isAppliedToMovies": true,
                "isAppliedToPerformances": false
            }
        ],
        "shows": [
            "/api/movie_shows/11",
            "/api/movie_shows/12",
            "/api/movie_shows/13",
            "/api/movie_shows/16"
        ]
    },
    {
        "@id": "/api/movies/17",
        "@type": "Movie",
        "title": "Бэтмен: Начало",
        "alternativeTitle": null,
        "originalTitle": "Batman Begins",
        "slug": "batman-begins",
        "description": "В детстве юный наследник огромного состояния Брюс Уэйн оказался свидетелем убийства своих родителей, и тогда он решил бороться с преступностью. Спустя годы он отправляется в путешествие по миру, чтобы найти способ восстановить справедливость. Обучение у мудрого наставника боевым искусствам дает ему силу и смелость. Вернувшись в родной город, Уэйн становится Бэтменом и ведет борьбу со злом.",
        "mainMediaObject": {
            "@id": "/api/media_objects/44",
            "@type": "MediaObject",
            "type": "MOVIE_COVER",
            "dirName": "2020/09",
            "fileName": "fixture_movie_cover_carnival.jpg",
            "mimeType": "image/jpeg",
            "width": 1023,
            "height": 680,
            "ratio": "1.5044118",
            "author": null,
            "description": null,
            "thumbnailUrl": "/uploads/media/2020/09/fixture_movie_cover_carnival_th.jpg",
            "url": "/uploads/media/2020/09/fixture_movie_cover_carnival.jpg"
        },
        "worldPremiereYear": 2005,
        "worldPremiereMonth": 5,
        "worldPremiereDay": 31,
        "russiaPremiereYear": 2005,
        "russiaPremiereMonth": 6,
        "russiaPremiereDay": 16,
        "budget": "$150 000 000",
        "duration": 140,
        "ageRating": "16+",
        "mpaaRating": "PG-13",
        "imdbId": "tt0372784",
        "imdbRating": "8.2",
        "kinopoiskId": "47237",
        "kinopoiskRating": "7.9",
        "website": "",
        "moverTrailerCode": "",
        "publishedCommentsCount": 16,
        "ratesCount": 27,
        "rating": "3.0",
        "genres": [
            {
                "@id": "/api/genres/18",
                "@type": "Genre",
                "name": "Боевик",
                "slug": "action",
                "isAppliedToBooks": true,
                "isAppliedToMovies": true,
                "isAppliedToPerformances": false
            }
        ],
        "shows": [
            "/api/movie_shows/29"
        ]
    },
    {
        "@id": "/api/movies/10",
        "@type": "Movie",
        "title": "Скайлайн 3",
        "alternativeTitle": null,
        "originalTitle": "Skylin3s16",
        "slug": "skyline-3",
        "description": "Через 15 лет после вторжения неизвестный вирус угрожает хрупкому сосуществованию дружественных инопланетных гибридов и людей. Родившаяся на космическом корабле мутант Роуз Корли сама испытывает трудности с управлением огневой рукой, когда на нее выходят члены сопротивления. Они предлагают девушке в составе хорошо подготовленного отряда, куда входит и ее брат-инопланетянин Трент, отправиться на вражескую планету и захватить сердечник разрушенного корабля, который поможет спасти человечество.",
        "mainMediaObject": {
            "@id": "/api/media_objects/36",
            "@type": "MediaObject",
            "type": "MOVIE_COVER",
            "dirName": "2020/08",
            "fileName": "fixture_movie_cover_classroom.jpg",
            "mimeType": "image/jpeg",
            "width": 1024,
            "height": 768,
            "ratio": "1.3333333",
            "author": null,
            "description": null,
            "thumbnailUrl": "/uploads/media/2020/08/fixture_movie_cover_classroom_th.jpg",
            "url": "/uploads/media/2020/08/fixture_movie_cover_classroom.jpg"
        },
        "worldPremiereYear": 2020,
        "worldPremiereMonth": 10,
        "worldPremiereDay": 25,
        "russiaPremiereYear": 2021,
        "russiaPremiereMonth": 3,
        "russiaPremiereDay": 11,
        "budget": null,
        "duration": 113,
        "ageRating": "16+",
        "mpaaRating": "R",
        "imdbId": "tt9387250",
        "imdbRating": "4.7",
        "kinopoiskId": "1282244",
        "kinopoiskRating": "4.6",
        "website": "",
        "moverTrailerCode": "0mnEr3Xm",
        "publishedCommentsCount": 16,
        "ratesCount": 22,
        "rating": "2.8",
        "genres": [
            {
                "@id": "/api/genres/15",
                "@type": "Genre",
                "name": "Приключения",
                "slug": "adventure",
                "isAppliedToBooks": false,
                "isAppliedToMovies": true,
                "isAppliedToPerformances": false
            }
        ],
        "shows": [
            "/api/movie_shows/14",
            "/api/movie_shows/15",
            "/api/movie_shows/17",
            "/api/movie_shows/20",
            "/api/movie_shows/22"
        ]
    },
    {
        "@id": "/api/movies/12",
        "@type": "Movie",
        "title": "Время",
        "alternativeTitle": null,
        "originalTitle": "In Time",
        "slug": "in-time",
        "description": "Добро пожаловать в мир, где время стало единственной и самой твердой валютой, где люди генетически запрограммированы так, что в 25 лет перестают стареть. Правда, последующие годы стоят денег. И вот богатые становятся практически бессмертными, а бедные обречены сражаться за жизнь. Уилл, бунтарь из гетто, несправедливо обвинен в убийстве с целью грабежа времени и теперь вынужден, захватив заложницу, пуститься в бега.",
        "mainMediaObject": {
            "@id": "/api/media_objects/49",
            "@type": "MediaObject",
            "type": "MOVIE_COVER",
            "dirName": "2020/12",
            "fileName": "fixture_movie_cover_people.jpg",
            "mimeType": "image/jpeg",
            "width": 1024,
            "height": 727,
            "ratio": "1.4085282",
            "author": null,
            "description": null,
            "thumbnailUrl": "/uploads/media/2020/12/fixture_movie_cover_people_th.jpg",
            "url": "/uploads/media/2020/12/fixture_movie_cover_people.jpg"
        },
        "worldPremiereYear": 2011,
        "worldPremiereMonth": 9,
        "worldPremiereDay": 30,
        "russiaPremiereYear": 2011,
        "russiaPremiereMonth": 10,
        "russiaPremiereDay": 27,
        "budget": "$40 000 000",
        "duration": 109,
        "ageRating": "12+",
        "mpaaRating": "PG-13",
        "imdbId": "tt1637688",
        "imdbRating": "6.7",
        "kinopoiskId": "517988",
        "kinopoiskRating": "7.3",
        "website": "",
        "moverTrailerCode": "",
        "publishedCommentsCount": 16,
        "ratesCount": 28,
        "rating": "3.3",
        "genres": [
            {
                "@id": "/api/genres/19",
                "@type": "Genre",
                "name": "Фантастика",
                "slug": "sci-fi",
                "isAppliedToBooks": true,
                "isAppliedToMovies": true,
                "isAppliedToPerformances": true
            }
        ],
        "shows": [
            "/api/movie_shows/30",
            "/api/movie_shows/31"
        ]
    },
    {
        "@id": "/api/movies/18",
        "@type": "Movie",
        "title": "Интерстеллар",
        "alternativeTitle": null,
        "originalTitle": "Interstellar",
        "slug": "interstellar",
        "description": "Когда засуха, пыльные бури и вымирание растений приводят человечество к продовольственному кризису, коллектив исследователей и учёных отправляется сквозь червоточину (которая предположительно соединяет области пространства-времени через большое расстояние) в путешествие, чтобы превзойти прежние ограничения для космических путешествий человека и найти планету с подходящими для человечества условиями.",
        "mainMediaObject": {
            "@id": "/api/media_objects/36",
            "@type": "MediaObject",
            "type": "MOVIE_COVER",
            "dirName": "2020/08",
            "fileName": "fixture_movie_cover_classroom.jpg",
            "mimeType": "image/jpeg",
            "width": 1024,
            "height": 768,
            "ratio": "1.3333333",
            "author": null,
            "description": null,
            "thumbnailUrl": "/uploads/media/2020/08/fixture_movie_cover_classroom_th.jpg",
            "url": "/uploads/media/2020/08/fixture_movie_cover_classroom.jpg"
        },
        "worldPremiereYear": 2014,
        "worldPremiereMonth": 10,
        "worldPremiereDay": 26,
        "russiaPremiereYear": 2014,
        "russiaPremiereMonth": 11,
        "russiaPremiereDay": 6,
        "budget": "$165 000 000",
        "duration": 169,
        "ageRating": "16+",
        "mpaaRating": "PG-13",
        "imdbId": null,
        "imdbRating": null,
        "kinopoiskId": null,
        "kinopoiskRating": null,
        "website": "",
        "moverTrailerCode": "",
        "publishedCommentsCount": 16,
        "ratesCount": 8,
        "rating": "2.8",
        "genres": [
            {
                "@id": "/api/genres/15",
                "@type": "Genre",
                "name": "Приключения",
                "slug": "adventure",
                "isAppliedToBooks": false,
                "isAppliedToMovies": true,
                "isAppliedToPerformances": false
            }
        ],
        "shows": [
            "/api/movie_shows/21"
        ]
    },
    {
        "@id": "/api/movies/9",
        "@type": "Movie",
        "title": "Ведьмак",
        "alternativeTitle": null,
        "originalTitle": "Witcher",
        "slug": "witcher",
        "description": "Ведьмак Геральт, мутант и убийца чудовищ, на своей верной лошади по кличке Плотва путешествует по Континенту. За тугой мешочек чеканных монет этот мужчина избавит вас от всякой настырной нечисти — хоть от чудищ болотных, оборотней и даже заколдованных принцесс. В сельской глуши местную девушку Йеннифэр, которой сильно не повезло с внешностью, зато посчастливилось иметь способности к магии, отец продаёт колдунье в ученицы. А малолетняя наследница королевства Цинтра по имени Цири вынуждена пуститься в бега, когда их страну захватывает империя Нильфгаард. Судьбы этих троих окажутся тесно связаны, но скоро сказка сказывается, да не скоро дело делается.",
        "mainMediaObject": {
            "@id": "/api/media_objects/49",
            "@type": "MediaObject",
            "type": "MOVIE_COVER",
            "dirName": "2020/12",
            "fileName": "fixture_movie_cover_people.jpg",
            "mimeType": "image/jpeg",
            "width": 1024,
            "height": 727,
            "ratio": "1.4085282",
            "author": null,
            "description": null,
            "thumbnailUrl": "/uploads/media/2020/12/fixture_movie_cover_people_th.jpg",
            "url": "/uploads/media/2020/12/fixture_movie_cover_people.jpg"
        },
        "worldPremiereYear": 2019,
        "worldPremiereMonth": 12,
        "worldPremiereDay": 20,
        "russiaPremiereYear": 2019,
        "russiaPremiereMonth": 12,
        "russiaPremiereDay": 20,
        "budget": null,
        "duration": 60,
        "ageRating": "18+",
        "mpaaRating": null,
        "imdbId": "tt5180504",
        "imdbRating": "8.2",
        "kinopoiskId": "1044004",
        "kinopoiskRating": "7.3",
        "website": "",
        "moverTrailerCode": "SoGCEBE",
        "publishedCommentsCount": 16,
        "ratesCount": 18,
        "rating": "2.6",
        "genres": [
            {
                "@id": "/api/genres/15",
                "@type": "Genre",
                "name": "Приключения",
                "slug": "adventure",
                "isAppliedToBooks": false,
                "isAppliedToMovies": true,
                "isAppliedToPerformances": false
            }
        ],
        "shows": [
            "/api/movie_shows/18"
        ]
    },
    {
        "@id": "/api/movies/13",
        "@type": "Movie",
        "title": "Соник в кино",
        "alternativeTitle": null,
        "originalTitle": "Sonic the Hedgehog",
        "slug": "sonic-the-hedgehog",
        "description": "Отвязный ярко-синий ёжик Соник из параллельного мира вместе с новообретённым лучшим другом-человеком по имени Том знакомится со сложностями жизни на Земле и противостоит злодейскому доктору Роботнику, который хочет пленить Соника и использовать его безграничные суперсилы для завоевания мирового господства.",
        "mainMediaObject": {
            "@id": "/api/media_objects/49",
            "@type": "MediaObject",
            "type": "MOVIE_COVER",
            "dirName": "2020/12",
            "fileName": "fixture_movie_cover_people.jpg",
            "mimeType": "image/jpeg",
            "width": 1024,
            "height": 727,
            "ratio": "1.4085282",
            "author": null,
            "description": null,
            "thumbnailUrl": "/uploads/media/2020/12/fixture_movie_cover_people_th.jpg",
            "url": "/uploads/media/2020/12/fixture_movie_cover_people.jpg"
        },
        "worldPremiereYear": 2020,
        "worldPremiereMonth": 1,
        "worldPremiereDay": 25,
        "russiaPremiereYear": 2020,
        "russiaPremiereMonth": 2,
        "russiaPremiereDay": 20,
        "budget": "$85 000 000",
        "duration": 99,
        "ageRating": "6+",
        "mpaaRating": "PG",
        "imdbId": null,
        "imdbRating": null,
        "kinopoiskId": null,
        "kinopoiskRating": null,
        "website": "",
        "moverTrailerCode": "",
        "publishedCommentsCount": 16,
        "ratesCount": 5,
        "rating": "3.6",
        "genres": [
            {
                "@id": "/api/genres/18",
                "@type": "Genre",
                "name": "Боевик",
                "slug": "action",
                "isAppliedToBooks": true,
                "isAppliedToMovies": true,
                "isAppliedToPerformances": false
            },
            {
                "@id": "/api/genres/15",
                "@type": "Genre",
                "name": "Приключения",
                "slug": "adventure",
                "isAppliedToBooks": false,
                "isAppliedToMovies": true,
                "isAppliedToPerformances": false
            }
        ],
        "shows": [
            "/api/movie_shows/19"
        ]
    },
    {
        "@id": "/api/movies/21",
        "@type": "Movie",
        "title": "Легенда №17",
        "alternativeTitle": "Легенда номер 17",
        "originalTitle": null,
        "slug": "legend-n17",
        "description": "Писарь из Санкт-Петербурга Николай Гоголь бросает вызов загадочному тёмному Всаднику, который жестоко расправляется с девушками в окрестностях села Диканька. Собрав команду из местного полицейского, пьяницы-доктора, суеверного кузнеца и странствующего философа-экзорциста, Гоголь пытается заманить злодея в ловушку, но на его пути встает самое жуткое порождение нечистой силы – Вий, один взгляд которого способен высосать душу смертного. Неожиданно для себя Гоголь выясняет, что с потусторонними силами его связывают не только таинственные видения.",
        "mainMediaObject": {
            "@id": "/api/media_objects/49",
            "@type": "MediaObject",
            "type": "MOVIE_COVER",
            "dirName": "2020/12",
            "fileName": "fixture_movie_cover_people.jpg",
            "mimeType": "image/jpeg",
            "width": 1024,
            "height": 727,
            "ratio": "1.4085282",
            "author": null,
            "description": null,
            "thumbnailUrl": "/uploads/media/2020/12/fixture_movie_cover_people_th.jpg",
            "url": "/uploads/media/2020/12/fixture_movie_cover_people.jpg"
        },
        "worldPremiereYear": 2013,
        "worldPremiereMonth": 4,
        "worldPremiereDay": 18,
        "russiaPremiereYear": 2013,
        "russiaPremiereMonth": 4,
        "russiaPremiereDay": 18,
        "budget": "€10 000 000",
        "duration": 134,
        "ageRating": "6+",
        "mpaaRating": "PG-13",
        "imdbId": null,
        "imdbRating": null,
        "kinopoiskId": "601564",
        "kinopoiskRating": "8.0",
        "website": "",
        "moverTrailerCode": "expVtj8",
        "publishedCommentsCount": 16,
        "ratesCount": 4,
        "rating": "3.8",
        "genres": [
            {
                "@id": "/api/genres/26",
                "@type": "Genre",
                "name": "Спорт",
                "slug": "sport",
                "isAppliedToBooks": true,
                "isAppliedToMovies": true,
                "isAppliedToPerformances": false
            }
        ],
        "shows": [
            "/api/movie_shows/26",
            "/api/movie_shows/28"
        ]
    },
    {
        "@id": "/api/movies/15",
        "@type": "Movie",
        "title": "Терминатор: Тёмные судьбы",
        "alternativeTitle": null,
        "originalTitle": "Terminator: Dark Fate",
        "slug": "terminator-dark-fate",
        "description": "Мексика. Милая девушка Даниэла Рамос, а для друзей просто Дани, вместе с братом приходит с утра работать на завод, но там выясняется, что их вскоре заменят автоматикой. И это не единственная угроза, которую представляют для девушки машины: тут же на неё нападает присланная из будущего и практически неубиваемая модель терминатора REV-9. Но на защиту Дани встает Грэйс - тоже прибывшая из будущего женщина, модифицировавшая свои боевые характеристики до терминаторского уровня. Вскоре к ним на помощь придёт и Сара Коннор, которая теперь превратилась в настоящую охотницу на роботов-убийц.",
        "mainMediaObject": {
            "@id": "/api/media_objects/54",
            "@type": "MediaObject",
            "type": "MOVIE_COVER",
            "dirName": "2021/03",
            "fileName": "fixture_movie_cover_alley.jpg",
            "mimeType": "image/jpeg",
            "width": 1023,
            "height": 681,
            "ratio": "1.5022026",
            "author": null,
            "description": null,
            "thumbnailUrl": "/uploads/media/2021/03/fixture_movie_cover_alley_th.jpg",
            "url": "/uploads/media/2021/03/fixture_movie_cover_alley.jpg"
        },
        "worldPremiereYear": 2019,
        "worldPremiereMonth": 10,
        "worldPremiereDay": 23,
        "russiaPremiereYear": 2019,
        "russiaPremiereMonth": 10,
        "russiaPremiereDay": 31,
        "budget": "$185 000 000",
        "duration": 109,
        "ageRating": "16+",
        "mpaaRating": "R",
        "imdbId": "tt6450804",
        "imdbRating": "6.2",
        "kinopoiskId": "1025082",
        "kinopoiskRating": "5.7",
        "website": "",
        "moverTrailerCode": "",
        "publishedCommentsCount": 16,
        "ratesCount": 7,
        "rating": "2.4",
        "genres": [
            {
                "@id": "/api/genres/18",
                "@type": "Genre",
                "name": "Боевик",
                "slug": "action",
                "isAppliedToBooks": true,
                "isAppliedToMovies": true,
                "isAppliedToPerformances": false
            }
        ],
        "shows": [
            "/api/movie_shows/32"
        ]
    },
    {
        "@id": "/api/movies/16",
        "@type": "Movie",
        "title": "Последний богатырь",
        "alternativeTitle": null,
        "originalTitle": null,
        "slug": "posledniy-bogatyr",
        "description": "Обычный парень Иван по воле случая переносится из современной Москвы в фантастическую страну Белогорье. В этом параллельном мире живут герои русских сказок, волшебство — неотъемлемая часть быта, а спорные вопросы решаются битвой на богатырских мечах. Неожиданно Иван оказывается в эпицентре борьбы светлых и тёмных сил, вот только непонятно, почему главная роль в происходящих событиях, по всеобщему мнению, уготована именно ему.",
        "mainMediaObject": {
            "@id": "/api/media_objects/44",
            "@type": "MediaObject",
            "type": "MOVIE_COVER",
            "dirName": "2020/09",
            "fileName": "fixture_movie_cover_carnival.jpg",
            "mimeType": "image/jpeg",
            "width": 1023,
            "height": 680,
            "ratio": "1.5044118",
            "author": null,
            "description": null,
            "thumbnailUrl": "/uploads/media/2020/09/fixture_movie_cover_carnival_th.jpg",
            "url": "/uploads/media/2020/09/fixture_movie_cover_carnival.jpg"
        },
        "worldPremiereYear": 2017,
        "worldPremiereMonth": 10,
        "worldPremiereDay": 26,
        "russiaPremiereYear": 2017,
        "russiaPremiereMonth": 10,
        "russiaPremiereDay": 26,
        "budget": null,
        "duration": 144,
        "ageRating": "12+",
        "mpaaRating": null,
        "imdbId": null,
        "imdbRating": null,
        "kinopoiskId": "976642",
        "kinopoiskRating": "6.8",
        "website": "",
        "moverTrailerCode": "",
        "publishedCommentsCount": 16,
        "ratesCount": 24,
        "rating": "2.8",
        "genres": [
            {
                "@id": "/api/genres/23",
                "@type": "Genre",
                "name": "Комедия",
                "slug": "comedy",
                "isAppliedToBooks": true,
                "isAppliedToMovies": true,
                "isAppliedToPerformances": true
            }
        ],
        "shows": [
            "/api/movie_shows/33",
            "/api/movie_shows/34"
        ]
    },
    {
        "@id": "/api/movies/20",
        "@type": "Movie",
        "title": "Гоголь. Вий",
        "alternativeTitle": null,
        "originalTitle": null,
        "slug": "gogol-viy",
        "description": "Писарь из Санкт-Петербурга Николай Гоголь бросает вызов загадочному тёмному Всаднику, который жестоко расправляется с девушками в окрестностях села Диканька. Собрав команду из местного полицейского, пьяницы-доктора, суеверного кузнеца и странствующего философа-экзорциста, Гоголь пытается заманить злодея в ловушку, но на его пути встает самое жуткое порождение нечистой силы – Вий, один взгляд которого способен высосать душу смертного. Неожиданно для себя Гоголь выясняет, что с потусторонними силами его связывают не только таинственные видения.",
        "mainMediaObject": {
            "@id": "/api/media_objects/40",
            "@type": "MediaObject",
            "type": "MOVIE_COVER",
            "dirName": "2020/09",
            "fileName": "fixture_movie_cover_city.jpg",
            "mimeType": "image/jpeg",
            "width": 1023,
            "height": 681,
            "ratio": "1.5022026",
            "author": null,
            "description": null,
            "thumbnailUrl": "/uploads/media/2020/09/fixture_movie_cover_city_th.jpg",
            "url": "/uploads/media/2020/09/fixture_movie_cover_city.jpg"
        },
        "worldPremiereYear": 2018,
        "worldPremiereMonth": 7,
        "worldPremiereDay": 13,
        "russiaPremiereYear": 2018,
        "russiaPremiereMonth": 4,
        "russiaPremiereDay": 5,
        "budget": null,
        "duration": 99,
        "ageRating": "16+",
        "mpaaRating": null,
        "imdbId": null,
        "imdbRating": null,
        "kinopoiskId": "1100779",
        "kinopoiskRating": "6.3",
        "website": "",
        "moverTrailerCode": "",
        "publishedCommentsCount": 16,
        "ratesCount": 26,
        "rating": "2.9",
        "genres": [
            {
                "@id": "/api/genres/15",
                "@type": "Genre",
                "name": "Приключения",
                "slug": "adventure",
                "isAppliedToBooks": false,
                "isAppliedToMovies": true,
                "isAppliedToPerformances": false
            }
        ],
        "shows": [
            "/api/movie_shows/23",
            "/api/movie_shows/24",
            "/api/movie_shows/25",
            "/api/movie_shows/27"
        ]
    }
]

const allMovies = (req, res) => {
    res.status(200)
    res.json({
        data: mockMovies,
        error_note: "",
        status: "Success"
    })
    res.end()
}

export default {allMovies}